'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Aircraft_Recognition_Test_2017.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A10 Thunderbolt II,A330 Voyager,Agusta A109,Agusta Westland AW101 Merlin,Airbus A400M Atlas,B1 Lancer,B2 Spirit,B52 Stratofortress,BAE Systems Hawk T1,Boeing E3 Sentry,Boeing KC-135 Stratotanker,Eurofighter Typhoon,F117 Nighthawk,F15C Eagle,F15E Strike Eagle,F16 Fighting Falcon,F22 Raptor,Lockheed AC130,Lockheed C141 Starlifter,Lockheed SR-71 Blackbird,Lockheed TriStar K1,McDonnell Douglas F4 Phantom,MQ-9 Reaper,Panavia Tornado GR4,Vickers VC10,Westland Lynx AH9,Aérospatiale Gazelle,Aérospatiale SA330 Puma, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Aircraft_List() As String
            Get
                Return ResourceManager.GetString("Aircraft_List", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property BEETHOVEN() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("BEETHOVEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 52.
        '''</summary>
        Friend ReadOnly Property NumberModern() As String
            Get
                Return ResourceManager.GetString("NumberModern", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 25.
        '''</summary>
        Friend ReadOnly Property NumberUnusual() As String
            Get
                Return ResourceManager.GetString("NumberUnusual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RAF() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RAF", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RAF1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RAF1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z0AS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z0AS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z0BS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z0BS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z1AS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z1AS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z1BS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z1BS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z2AS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z2AS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z2BS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z2BS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z3AS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z3AS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z3BS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z3BS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z4AS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z4AS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z4BS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z4BS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z5AS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z5AS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z5BS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z5BS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z6AS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z6AS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Z6BS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Z6BS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
